export const colors = [
  '0, 0, 255',
  '255, 0, 0',
  '0, 255, 0',
  '255, 166, 0',
  '192, 0, 192',
  '0, 255, 255',
  '255, 0, 255',
  '255, 255, 0',
];

export const aboutISS = {
  name: 'ISS',
  about: `The International Space Station (ISS) is the largest human-made structure ever assembled in space and serves as a permanently inhabited laboratory in low Earth orbit. Orbiting approximately 400 kilometers (250 miles) above Earth, the station travels at a speed of about 28,000 kilometers per hour (17,500 miles per hour), completing roughly 16 orbits each day. This means that astronauts aboard the ISS experience a sunrise and sunset about every 90 minutes. The station is a joint project involving multiple space agencies, including NASA, Roscosmos, European Space Agency, Japan Aerospace Exploration Agency, and Canadian Space Agency. Construction began in 1998 with the launch of the Russian Zarya module, and the station has continuously hosted crews since November 2000.\n\nThe ISS functions as a unique scientific laboratory where researchers can study the effects of microgravity on physical, biological, and chemical processes. Experiments conducted aboard the station have contributed to advances in medicine, materials science, fluid dynamics, plant growth, and human physiology. Scientists use the ISS to investigate how the human body adapts to long-duration spaceflight, including changes to muscles, bones, vision, and the cardiovascular system. These studies help prepare for future missions to the Moon and Mars while also producing knowledge that can benefit healthcare and technology development on Earth.\n\nThe station consists of interconnected modules that provide living quarters, laboratories, storage areas, and docking ports for visiting spacecraft. Large solar arrays generate electrical power, while sophisticated life-support systems recycle air and water to reduce the need for resupply from Earth. Cargo and crew are transported to and from the ISS by spacecraft such as SpaceX Dragon, Soyuz, and other international vehicles. Astronauts regularly perform spacewalks to install new equipment, conduct maintenance, and upgrade station systems. The ISS is designed as both a research platform and a testbed for technologies needed for future deep-space exploration.\n\nBeyond its scientific achievements, the ISS represents one of the most successful examples of international cooperation in human history. Engineers, scientists, and astronauts from many nations have worked together for decades to build, operate, and expand the station despite political and cultural differences. The knowledge gained from the ISS continues to influence future exploration programs, including planned missions to the Moon through the Artemis program and eventual crewed journeys to Mars. As it enters the later stages of its operational life, the ISS remains a symbol of what humanity can accomplish through collaboration, scientific curiosity, and a shared commitment to exploring space.`,
};

export const aboutHST = {
  name: 'Hubble',
  about: `The Hubble Space Telescope (HST) is one of the most influential scientific instruments ever built and has transformed humanity's understanding of the universe. Launched into low Earth orbit aboard the Space Shuttle Discovery in April 1990, Hubble operates at an altitude of approximately 540 kilometers (335 miles), completing one orbit around Earth every 95 minutes. The telescope was developed through a partnership between NASA and the European Space Agency. Unlike ground-based observatories, Hubble operates above Earth's atmosphere, allowing it to capture exceptionally sharp images without atmospheric distortion and observe wavelengths of light that are partially blocked from the ground.\n\nHubble's primary mission is to observe distant stars, galaxies, nebulae, planets, and other celestial objects across the visible, ultraviolet, and near-infrared regions of the electromagnetic spectrum. Over more than three decades of operation, it has contributed to thousands of scientific discoveries, including refining the age and expansion rate of the universe, confirming the existence of supermassive black holes at the centers of galaxies, and providing evidence for the accelerating expansion of the universe. It has also produced detailed observations of planets within our Solar System, monitored the formation of stars and planetary systems, and captured some of the deepest images of the cosmos ever recorded, revealing galaxies billions of light-years away.\n\nThe telescope measures about 13.2 meters (43.5 feet) in length, weighs approximately 11,000 kilograms (24,000 pounds), and features a primary mirror 2.4 meters (7.9 feet) in diameter. Hubble was designed to be serviced by astronauts, and five servicing missions carried out by the Space Shuttle between 1993 and 2009 repaired defects, replaced scientific instruments, and upgraded onboard systems. These missions greatly extended the telescope's operational lifetime and improved its capabilities, allowing it to remain one of the world's most productive astronomical observatories long after its original planned lifespan.\n\nBeyond its scientific achievements, the Hubble Space Telescope has become an icon of space exploration and public science. Its breathtaking images of galaxies, nebulae, and star clusters have inspired millions of people worldwide and helped make astronomy more accessible to the public. Although newer observatories such as the James Webb Space Telescope offer advanced capabilities in infrared astronomy, Hubble continues to complement them by providing high-resolution observations in visible and ultraviolet light. Together, these telescopes are expanding our knowledge of the universe, ensuring that Hubble's legacy remains central to modern astronomical research.`,
};

export const aboutCSS = {
  name: 'CSS',
  about: `The Tiangong space station, commonly referred to as the Chinese Space Station (CSS), is China's permanently inhabited space laboratory in low Earth orbit. Orbiting at an altitude of approximately 340–450 kilometers (210–280 miles), the station travels at about 28,000 kilometers per hour (17,500 miles per hour), completing an orbit around Earth roughly every 90 minutes. Tiangong, which means "Heavenly Palace" in Chinese, is operated by the China Manned Space Agency. The station's construction began in 2021 with the launch of the Tianhe core module and was largely completed in 2022 with the addition of the Wentian and Mengtian laboratory modules. It serves as China's primary platform for long-term human presence and scientific research in space.\n\nThe CSS is designed to support a crew of three astronauts during normal operations, with the capacity to accommodate up to six during crew rotation periods. Astronauts live and work aboard the station for missions lasting several months, conducting experiments in biology, medicine, physics, astronomy, and Earth observation. The microgravity environment allows scientists to study processes that are difficult or impossible to observe on Earth, contributing to research on advanced materials, fluid behavior, combustion, and the effects of long-duration spaceflight on the human body. These experiments support both scientific discovery and the development of technologies needed for future lunar and deep-space missions.\n\nThe station consists of three main pressurized modules connected in a T-shaped configuration. The Tianhe core module provides crew living quarters, command systems, and life-support equipment, while the Wentian and Mengtian laboratory modules house scientific instruments, experiment racks, and additional control systems. Large solar arrays generate electrical power, and advanced recycling systems help conserve water and air for long-duration missions. Crews and supplies are transported to the station using the Shenzhou spacecraft and Tianzhou resupply vehicles. Astronauts also perform regular spacewalks to install new equipment, maintain external systems, and support scientific operations.\n\nThe Chinese Space Station represents a major milestone in China's human spaceflight program and demonstrates the country's growing capabilities in space exploration. It provides an independent platform for conducting long-term research in orbit while also supporting international scientific cooperation through selected research partnerships. As China continues developing technologies for lunar exploration and future crewed missions beyond Earth orbit, the CSS serves as an important testing ground for life-support systems, spacecraft operations, and advanced engineering. It stands as a symbol of China's expanding role in space science and its long-term commitment to human exploration of space.`,
};
